// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package follow

import (
	"context"

	"beyond/application/follow/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty          = pb.Empty
	FansItem       = pb.FansItem
	FansListReq    = pb.FansListReq
	FansListResp   = pb.FansListResp
	FollowItem     = pb.FollowItem
	FollowListReq  = pb.FollowListReq
	FollowListResp = pb.FollowListResp
	FollowReq      = pb.FollowReq
	UnFollowReq    = pb.UnFollowReq

	Follow interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*Empty, error)
		UnFollow(ctx context.Context, in *UnFollowReq, opts ...grpc.CallOption) (*Empty, error)
		FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*FollowListResp, error)
		FansList(ctx context.Context, in *FansListReq, opts ...grpc.CallOption) (*FansListResp, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

func (m *defaultFollow) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultFollow) UnFollow(ctx context.Context, in *UnFollowReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.UnFollow(ctx, in, opts...)
}

func (m *defaultFollow) FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*FollowListResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.FollowList(ctx, in, opts...)
}

func (m *defaultFollow) FansList(ctx context.Context, in *FansListReq, opts ...grpc.CallOption) (*FansListResp, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.FansList(ctx, in, opts...)
}
