// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"beyond/application/article/rpc/internal/logic"
	"beyond/application/article/rpc/internal/svc"
	"beyond/application/article/rpc/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *pb.PublishReq) (*pb.PublishResp, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) Articles(ctx context.Context, in *pb.ArticlesReq) (*pb.ArticlesResp, error) {
	l := logic.NewArticlesLogic(ctx, s.svcCtx)
	return l.Articles(in)
}

func (s *ArticleServer) ArticleDelete(ctx context.Context, in *pb.ArticleDeleteReq) (*pb.Empty, error) {
	l := logic.NewArticleDeleteLogic(ctx, s.svcCtx)
	return l.ArticleDelete(in)
}

// rpc ArticleDelete(ArticleDeleteReq) returns (google.protobuf.Empty);
func (s *ArticleServer) ArticleDetail(ctx context.Context, in *pb.ArticleDetailReq) (*pb.ArticleDetailResp, error) {
	l := logic.NewArticleDetailLogic(ctx, s.svcCtx)
	return l.ArticleDetail(in)
}
