// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package like

import (
	"context"

	"beyond/application/like/rpc/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsThumbupReq  = service.IsThumbupReq
	IsThumbupResp = service.IsThumbupResp
	ThumbupReq    = service.ThumbupReq
	ThumbupResp   = service.ThumbupResp
	UserThumbup   = service.UserThumbup

	Like interface {
		Thumbup(ctx context.Context, in *ThumbupReq, opts ...grpc.CallOption) (*ThumbupResp, error)
		IsThumbup(ctx context.Context, in *IsThumbupReq, opts ...grpc.CallOption) (*IsThumbupResp, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) Thumbup(ctx context.Context, in *ThumbupReq, opts ...grpc.CallOption) (*ThumbupResp, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.Thumbup(ctx, in, opts...)
}

func (m *defaultLike) IsThumbup(ctx context.Context, in *IsThumbupReq, opts ...grpc.CallOption) (*IsThumbupResp, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.IsThumbup(ctx, in, opts...)
}
