// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	logic2 "beyond/application/user/rpc/internal/logic"
	"beyond/application/user/rpc/internal/svc"
	service2 "beyond/application/user/rpc/service"
	"context"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	service2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *service2.RegisterRequest) (*service2.RegisterResponse, error) {
	l := logic2.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) FindById(ctx context.Context, in *service2.FindByIdRequest) (*service2.FindByIdResponse, error) {
	l := logic2.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

func (s *UserServer) FindByMobile(ctx context.Context, in *service2.FindByMobileRequest) (*service2.FindByMobileResponse, error) {
	l := logic2.NewFindByMobileLogic(ctx, s.svcCtx)
	return l.FindByMobile(in)
}

func (s *UserServer) SendSms(ctx context.Context, in *service2.SendSmsRequest) (*service2.SendSmsResponse, error) {
	l := logic2.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}
