// Code generated by goctl. DO NOT EDIT.
package types

type UploadCoverResp struct {
	CoverUrl string `json:"cover_url"`
}

type PublishReq struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	Description string `json:"description"`
	Cover       string `json:"cover"`
}

type PublishResp struct {
	ArticleId int64 `json:"articleId"`
}
